# TODO this is not that good idea afterall
# when I want to do select&replace some text and I have the new text ready
# in the clipboard, the double-click to select the replaced text override
# the new text in the clipboard
# synchronizing system and selection clipboard buffers
xrdb -merge ~/.Xresources
autocutsel -fork &
autocutsel -selection PRIMARY -fork &
#/usr/bin/start-pulseaudio-x11 &
exec i3 -V >> ~/.i3/i3log 2>&1
