---
# Dotfiles playbook, TODO more description

# TODO the hardcoded dotfiles path is a problem
# Maybe stop using symlink and just place the file to the location?
- name: Symlink my dotfiles
  copy: src=~/dev/projects/etc/dotfiles/{{ item.path }}
        dest=~/{{ item.dest }}
        force=yes
  with_items:
    - { path: 'vim/vimrc', dest: '.vimrc'}
    - { path: 'git/gitconfig', dest: '.gitconfig'}
    - { path: 'zsh/zshrc', dest: '.zshrc'}
    - { path: 'zsh/zsh_aliases.sh', dest: '.zsh_aliases.sh'}
    - { path: 'zsh/zsh_functions.sh', dest: '.zsh_functions.sh'}
    - { path: 'zsh/stibi.zsh-theme', dest: '.oh-my-zsh/themes/stibi.zsh-theme'}
