---

- name: Install common packages
  sudo: yes
  action: >
    {{ ansible_pkg_mgr }}
    name={{ item }}
    state=present
  with_items:
    - git
    - vim
    - htop
    - mc
  tags: [common-packages]

# TODO vim configuration, auto coloring, etc, dotfiles thing…
#- include: dotfiles.yml
