---
# TODO refactoring
# TODO not all machines with Archlinux, pacman should not be hardcoded here

- name: Install common packages
  pacman: >
    name={{ item }}
    state=present
  with_items:
    - git
    - vim
    - htop

# TODO vim configuration, auto coloring, etc, dotfiles thing…

#- include: dotfiles.yml
