---
# My mek related configuration tasks

# TODO wheel s NOPASSWD v sudoers

- name: Setup hostname
  hostname: name=mek

- name: Install packages on mek
  pacman: >
    name={{ item }}
    state=present
  sudo: yes
  with_items:
    - rsyslog

#- include: st2.yml
