---
# My mek related configuration tasks

# ~/.ssh/config TODO
# TODO wheel s NOPASSWD v sudoers
# TODO ~/.malina_sambacreds soubor
# TODO samba na maline v /etc/fstab
# TODO presunout sem konfiguraci synaptics z svim /etc/X11/xorg.conf.d/50-synaptics.conf

- name: Setup hostname
  hostname: name=mek

- name: Install packages on mek
  pacman: >
    name={{ item }}
    state=present
  sudo: yes
  with_items:
    - rsyslog

#- include: st2.yml
- include: i3.yml
