---
# My mek related configuration tasks

# TODO wheel s NOPASSWD v sudoers

- name: Install packages
  pacman: >
    name={{ item }}
    state=present
  sudo: True
  with_items:
    - zsh

- name: Install oh-my-zsh
  git: >
    repo=https://github.com/robbyrussell/oh-my-zsh.git
    dest=~/.oh-my-zsh
    update=yes

#- include: st2.yml
