---
# manual mount:
# sudo mount -t cifs //MALINA/usbdisk /mnt/malina_samba -o user=stibi,password=password,workgroup=workgroup,ip=192.168.2.134

- name: Enable Samba services
  sudo: yes
  service: >
    name={{ item }}
    enabled=yes
  with_items:
    - smbd.service
    - nmbd.service
  tags: [samba]

- name: Create unix accounts for samba users
  sudo: yes
  user: >
    name={{ item.username }}
    groups=users
    state=present
  with_items: samba.users
  tags: [samba]

- name: Create samba users
  sudo: yes
  shell: 'printf "{{ item.password }}\n{{ item.password }}\n" | smbpasswd -a -s {{ item.username }}'
  with_items: samba.users
  tags: [samba]

- name: Copy default samba config file
  sudo: yes
  copy: >
    src=smb.conf
    dest=/etc/samba/smb.conf
    owner=root
    group=root
    validate='testparm -s %s'
  tags: [samba]
  notify: [start samba services]
