---
- name: Enable transmission service
  sudo: yes
  service: >
    name=transmission
    enabled=yes
  tags: [transmission]

- name: Stop transmission before configuration changes
  sudo: yes
  service: >
    name=transmission
    state=stopped
  tags: [transmission]

# The "2" in mode is setgid
- name: Setup download dirs permission
  sudo: yes
  file: >
    state=directory
    mode=2777
    owner=stibi
    group=users
    recurse=yes
    path={{ transmission.torrents_dir }}
  tags: [transmission]

- name: Configure transmission-daemon
  sudo: yes
  template: >
    src=transmission_settings.json.j2
    dest=/var/lib/transmission/.config/transmission-daemon/settings.json
  notify: [restart transmission]
  tags: [transmission]

- name: Setup script to handle completed torrents
  sudo: yes
  template: >
    src=handleTorrents.sh.j2
    dest=/home/stibi/bin/handleTorrents.sh
    owner=stibi
    group=users
    mode=0744
  tags: [transmission]

- name: Setup passwordless sudo for the torrent handling script
  sudo: yes
  copy: >
    src=torrents_sudoers
    dest=/etc/sudoers.d/torrents
    owner=root
    group=root
  tags: [transmission]
