---
- name: Enable transmission service
  sudo: yes
  service: >
    name=transmission
    enabled=yes
  tags: [transmission]

- name: Stop transmission before configuration changes
  sudo: yes
  service: >
    name=transmission
    state=stopped
  tags: [transmission]

# The "2" in mode is setgid
- name: Setup download dirs permission
  sudo: yes
  file: >
    state=directory
    mode=2777
    group=users
    owner=stibi
    recurse=yes
    path={{ transmission.torrents_dir }}
  tags: [transmission]

- name: Configure transmission-daemon
  sudo: yes
  template: >
    src=transmission_settings.json.j2
    dest=/var/lib/transmission/.config/transmission-daemon/settings.json
  notify: [restart transmission]
  tags: [transmission]
