---
# python2 -c 'import crypt; print crypt.crypt("terriblepassword", "$1$SomeSalt$")'
# Don't forget to define a variable file for a host in groups_vars, with a variable "my_user_pass", defining a password for the user on a particular host

# TODO ujistit se, ze zsh se neinstaluje nikde jinde, nejak jinak
- name: Install ZSH
  sudo: yes
  pacman: >
    name=zsh
    state=present
  tags: [user, zsh]

- name: Install oh-my-zsh
  sudo: yes
  sudo_user: stibi
  git: >
    repo=https://github.com/robbyrussell/oh-my-zsh.git
    dest=~/.oh-my-zsh
    update=yes
  tags: [user, zsh]

- name: stat ~/.zshrc.orig
  sudo: yes
  sudo_user: stibi
  stat: path=~/.zshrc.orig
  register: zshrc_orig_stat
  tags: [user, zsh]

- name: Backup original zsh configuration
  sudo: yes
  sudo_user: stibi
  command: mv ~/.zshrc ~/.zshrc.orig
  when: not zshrc_orig_stat.stat.exists
  tags: [user, zsh]

# TODO rename, refactor
- name: stat ~/.zshrc
  sudo: yes
  sudo_user: stibi
  stat: path=~/.zshrc
  register: zshrc_stat
  tags: [user, zsh]

- name: Create a new Zsh config from a template
  sudo: yes
  sudo_user: stibi
  command: cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
  when: not zshrc_stat.stat.exists
  tags: [user, zsh]

- name: Create sudo group
  sudo: yes
  group: name=sudo state=present
  tags: [user]

- name: Create non-priviledged user for me
  sudo: yes
  user: >
    name=stibi
    createhome=yes
    password={{ my_user_pass }}
    generate_ssh_key=yes
    ssh_key_bits=2048
    groups=users,sudo
    shell=/usr/bin/zsh
    state=present
  tags: [user, ssh, sshkey]

- name: Add SSH pubkey from my workstation to authorized_keys
  sudo: yes
  authorized_key: >
    state=present
    user=stibi
    key="{{ lookup('file', 'stibi_at_mek_rsa.pub') }}"
    manage_dir=yes
  tags: [user]

- name: Enable sudo for members of the sudo group
  sudo: yes
  lineinfile: >
    dest=/etc/sudoers
    regexp='^#? ?%sudo ALL=\(ALL\) ALL'
    line='%sudo ALL=(ALL) ALL'
    validate='visudo -cf %s'
    state=present
  tags: [user]

- name: Setup targetpw option for sudo
  sudo: yes
  lineinfile: >
    dest=/etc/sudoers
    regexp='^#? ?Defaults targetpw'
    line='Defaults targetpw'
    validate='visudo -cf %s'
    state=present
  tags: [user]

- name: Create ~/bin for my non-priviledged user to place my scripts there
  sudo: yes
  file: >
    dest=/home/stibi/bin
    owner=stibi
    group=users
    state=directory
  tags: [user]

# TODO nope, not yet done, too many hairs pulled out
# - name: Add ~/bin to PATH
#   sudo: yes
#   lineinfile: >
#     dest=~/.zshrc
#     backrefs=true
#     regexp='^export PATH="?(([a-zA-Z0-9/.\-@$_]+:?)*~/bin/?:?([a-zA-Z0-9/.\-@$_]+:?)*)"?'
#     line=
#     state=present
#     onlyif binToPath is true
#   tags: [user, pathdebug]
