# Ne dobry, protoze to nabootuje do konzole, do tmuxu, ja spustim ve tmuxu startx a uvnitr v i3 uz nepustim dalsi tmux, protoze to bezi v tmuxu
# Vyresit jinak
# If not running interactively, do not do anything
#[[ $- != *i* ]] && return
#[[ -z "$TMUX" ]] && exec tmux

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Workaournd for this issue: https://github.com/archlinuxfr/yaourt/issues/11
ttyctl -f

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="stibi_tmux"

if [ -f ~/.zsh_functions.sh ]; then
    source ~/.zsh_functions.sh
fi

if [ -f ~/.zsh_aliases.sh ]; then
    source ~/.zsh_aliases.sh
fi

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# TODO kouknout n toto
# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/home/stibi/.rvm/gems/ruby-2.0.0-p353/bin:/home/stibi/.rvm/gems/ruby-2.0.0-p353@global/bin:/home/stibi/.rvm/rubies/ruby-2.0.0-p353/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/build-tools/19/:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/java6/bin:/opt/java6/db/bin:/opt/java6/jre/bin:/usr/bin/core_perl:$ORACLE_HOME/bin:/home/stibi/bin"

export EDITOR='vim'

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# ssh-agent for my keys
. ~/bin/agent-startup.sh

# TODO still needed?
eval `dircolors /etc/dir_colors`

export HISTSIZE=1000000000
export SAVEHIST=$HISTSIZE
setopt EXTENDED_HISTORY

# !! Temporary workaround for grep and the deprecation of GREP_OPTIONS in grep 2.21
alias grep="/usr/bin/grep $GREP_OPTIONS"
unset GREP_OPTIONS

# bindovani Home/End klaves (fň + vlevo/vpravo)
# V KDE/Konsole to funguje i bez tech bindkey, ale v urvxt z nejakeho duvodu ne
# nevim proc a stve me, ze nevim proc
# Takze TODO tady. Ma to co delat s $TERM rekl bych.
bindkey "\e[7~" beginning-of-line
bindkey "\e[8~" end-of-line
