# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

TERM="screen-256color"

# Workaournd for this issue: https://github.com/archlinuxfr/yaourt/issues/11
ttyctl -f

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="stibi_tmux"

if [ -f ~/.zsh_functions.sh ]; then
    source ~/.zsh_functions.sh
fi

if [ -f ~/.zsh_aliases.sh ]; then
    source ~/.zsh_aliases.sh
fi

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# BACKUP - tohle tehdy fixlo problem s chefem & vagrant & vendavo oracle box buildem
#export PATH="/home/stibi/.rvm/gems/ruby-1.9.2-p320/bin:/home/stibi/.rvm/gems/ruby-1.9.2-p320@global/bin:/home/stibi/.rvm/rubies/ruby-1.9.2-p320/bin:/home/stibi/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/build-tools/19/:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/java6/bin:/opt/java6/db/bin:/opt/java6/jre/bin:/usr/bin/core_perl:$ORACLE_HOME/bin:/home/stibi/bin"
export PATH="/home/stibi/.rvm/gems/ruby-2.0.0-p353/bin:/home/stibi/.rvm/gems/ruby-2.0.0-p353@global/bin:/home/stibi/.rvm/rubies/ruby-2.0.0-p353/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/build-tools/19/:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/java6/bin:/opt/java6/db/bin:/opt/java6/jre/bin:/usr/bin/core_perl:$ORACLE_HOME/bin:/home/stibi/bin"

# export MANPATH="/usr/local/man:$MANPATH"

# # Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

export EDITOR='vim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Presunuto do /etc/profile
#eval $(ssh-agent)
#source ~/.keychain/mek-sh
. ~/bin/agent-startup.sh

eval `dircolors /etc/dir_colors`

# Instead of overwriting the history file, instead it appends lines. This helps if there are multiple zsh sessions, so that they don't just overwrite the history
setopt APPEND_HISTORY
# Each shell, as it runs a command, appends the command to the history file right away. This way, each shell has a unique history while it's running, but stores an interleaved set of history in the file. Starting a new shell or restarting my X session, results in having access to my history as I executed it previously.
setopt INC_APPEND_HISTORY
# If the same command is run multiple times in a row, it is only entered in history once.
setopt HIST_IGNORE_DUPS
