---
packages: [ zsh, vim, rsyslog, transmission-cli ]
transmission:
  port: 9091
  user: torrentman
  pass: "{{ vaulted_transmission_pass }}"
  completed_dir: /mnt/usbdisk/torrents/completed
  inprogreess_dir: /mnt/usbdisk/torrents/inprogress
