---
# TODO avahi se tady instaluje? Mam roli...
# TODO nodejs je nutne? To si nainstaluje ten co to potrebuje, ne?
packages: [ rsyslog, transmission-cli, nfs-utils, avahi, nss-mdns, fakeroot, binutils, yajl, gcc, make, ntp, samba, nodejs, wget, patch ]

# TODO transmission do vlastni role
transmission:
  port: 9091
  user: torrentman
  pass: "{{ vaulted_transmission_pass }}"
  torrents_dir: /mnt/usbdisk/torrents
  completed_dir: /mnt/usbdisk/torrents/completed
  inprogreess_dir: /mnt/usbdisk/torrents/inprogress

nfs:
  movies_dir: /mnt/usbdisk/filmy

# TODO stibi user uz tam je, diky myuser roli, takhle bych ho akorat prepsal
samba:
  users:
    #- {username: "stibi", password : "{{ vaulted_stibi_pass }}"}
    - {username: "lena", password : "{{ vaulted_lena_pass }}"}

sensors:
  ds1820_sensor_id: 28-0000060a382b

rss2email:
  feeds:
    - https://what-if.xkcd.com/feed.atom
