---
# TODO avahi se tady instaluje? Mam roli...
packages: [ rsyslog, transmission-cli, nfs-utils, avahi, nss-mdns, fakeroot, binutils, yajl, gcc, make, ntp, samba, nodejs ]

transmission:
  port: 9091
  user: torrentman
  pass: "{{ vaulted_transmission_pass }}"
  torrents_dir: /mnt/usbdisk/torrents
  completed_dir: /mnt/usbdisk/torrents/completed
  inprogreess_dir: /mnt/usbdisk/torrents/inprogress

samba:
  users:
    - {username: "stibi", password : "{{ vaulted_stibi_pass }}"}
    - {username: "lena", password : "{{ vaulted_lena_pass }}"}

sensors:
  ds1820_sensor_id: 28-0000060a382b

