---
- name: restart transmission
  sudo: yes
  service: >
    name=transmission
    state=restarted

- name: start samba services
  sudo: yes
  service: >
    name={{ item }}
    state=restarted
  with_items:
    - smbd.service
    - nmbd.service
