---
- name: restart transmission
  sudo: yes
  service: >
    name=transmission
    state=restarted

- name: reload exports
  sudo: yes
  command: exportfs -ra

- name: restart rpcbind
  sudo: yes
  service: >
    name=rpcbind
    state=restarted

- name: restart nfs-server
  sudo: yes
  service: >
    name=nfs-server
    state=restarted
