---

- name: Configure my workstation - mek
  hosts: workstation
  user: stibi
  roles:
    - mek

# SSH connection with root user enabled from local network
- name: Configure my router - brepta
  hosts: brepta
  user: root
  roles:
    - brepta

- name: Configure raspi n1 - malina
  hosts: malina
  user: ansible
  roles:
    - malina

- name: Configure oblacek server
  hosts: oblacek
  user: ansible
  roles:
    - oblacek

#- name: apply common configuration to all nodes
#  hosts: all
#  user: stibi
#  roles:
#    - common

# TODO: my username definition to variables
#- name: Configure my mek
#  hosts: localhost
#  user: stibi
#  roles:
#    - mek

#- name:
# TODO: machine specific playbooks
# mek
# malina
# oblacek
