---

- name: Configure my workstation - mek
  hosts: workstation
  user: stibi
  roles:
    - common
    - mek

# SSH connection with root user enabled from local network
- name: Configure my router - brepta
  hosts: brepta
  user: root
  vars_files:
    - roles/brepta/vars/vault.yml
    - roles/brepta/vars/main.yml
  roles:
    - myuser
    - brepta

# TODO tady chybi avahi role, zkontrolovat i ostatni
# TODO I don't like these vars_files, any better solution?
- name: Configure raspi - malina
  hosts: malina
  vars_files:
    - roles/malina/vars/vault.yml
    - roles/malina/vars/main.yml
  roles:
    - common
    - myuser
    - malina
    - ds18b20-service
    - ssh
    - { role: autossh, remote_forwarded_ssh_port: 4444 }

- name: Configure oblacek server
  hosts: oblacek
  user: ansible
  roles:
    - common
    - myuser
    - oblacek

- name: Configure raspi - hopspi
  hosts: hopspi
  user: ansible
  vars_files:
  - roles/hopspi/vars/vault.yml
  - roles/hopspi/vars/main.yml
  roles:
    - common
    - myuser
    - hopspi
    - ssh
    - ds18b20-service
    - avahi
    - { role: autossh, remote_forwarded_ssh_port: 3333 }
