---

- name: Configure my workstation - mek
  hosts: workstation
  user: stibi
  roles:
    - common
    - ntp-ansible-role
    - mek

# SSH connection with root user enabled from local network
- name: Configure my router - brepta
  hosts: brepta
  user: root
  vars_files:
    - roles/brepta/vars/vault.yml
    - roles/brepta/vars/main.yml
  roles:
    - common
    # TODO the ntp role needs openwrt/turris support
    #- ntp-ansible-role
    #- myuser
    - brepta

# TODO tady chybi avahi role, zkontrolovat i ostatni
# TODO I don't like these vars_files, any better solution?
- name: Configure raspi - malina
  hosts: malina
  vars_files:
    - roles/malina/vars/vault.yml
    - roles/malina/vars/main.yml
  roles:
    - role: common
    - role: myuser
    - role: ntp-ansible-role
    - role: malina
    - role: ds18b20-service
    - role: ssh
    - role: autossh
      remote_forwarded_ssh_port: 4444
    - role: emoncms-ansible-role
    - role: emonhub-ansible-role
      rfm12pi_group: 210
      rfm12pi_freq: 868
      rfm12pi_baseid: 1
      emonhub_emoncms_apikey: "6a272ec63787809a59e4f56bfaac4f3b"
    - role: nodered-ansible-role
    - role: mosquitto-ansible-role
    - role: nfs-ansible-role
      allowed_clients: 192.168.2.0/24
      nfs_root: /srv/nfs/
      nfs_root_options: rw,fsid=root,no_subtree_check,insecure
      nfs_mount_options: rw,no_subtree_check,nohide,insecure
      exports:
        - { device: '/mnt/usbdisk', nfs_mount: '/srv/nfs/malina_disk' }
        - { device: '/mnt/usbdisk/serialy', nfs_mount: '/srv/nfs/serialy' }
        - { device: '/mnt/usbdisk/filmy', nfs_mount: '/srv/nfs/filmy' }
        - { device: '/mnt/usbdisk/torrents', nfs_mount: '/srv/nfs/torrenty' }
        - { device: '/mnt/usbdisk/pictures', nfs_mount: '/srv/nfs/pictures' }

- name: Configure oblacek server
  hosts: oblacek
  user: ansible
  roles:
    - common
    - myuser
    - ntp-ansible-role
    - oblacek

# - name: Configure raspi - hopspi
#   hosts: hopspi
#   user: ansible
#   vars_files:
#   - roles/hopspi/vars/vault.yml
#   - roles/hopspi/vars/main.yml
#   roles:
#     - common
#     - myuser
#     - hopspi
#     - ssh
#     - ds18b20-service
#     - avahi
#     - { role: autossh, remote_forwarded_ssh_port: 3333 }
