---

- name: Configure my workstation - mek
  hosts: workstation
  user: stibi
  roles:
    - mek

# SSH connection with root user enabled from local network
- name: Configure my router - brepta
  hosts: brepta
  user: root
  vars_files:
    - roles/brepta/vars/vault.yml
    - roles/brepta/vars/main.yml
  roles:
    - myuser
    - brepta

# TODO I don't like these vars_files, any better solution?
- name: Configure raspi - malina
  hosts: malina
  user: ansible
  vars_files:
    - roles/malina/vars/vault.yml
    - roles/malina/vars/main.yml
  roles:
    - myuser
    - malina

- name: Configure oblacek server
  hosts: oblacek
  user: ansible
  roles:
    - myuser
    - oblacek

- name: Configure raspi - hopspi
  hosts: hopspi
  user: ansible
  vars_files:
  - roles/hopspi/vars/vault.yml
  - roles/hopspi/vars/main.yml
  roles:
    - myuser
    - hopspi
    #- ds18b20-nodejs-service
