---
# Main playbook, TODO: lepsi popis :)

- name: apply common configuration to all nodes
  hosts: all
  user: ansible
  roles:
    - common

# TODO: my username definition to variables
- name: Configure my mek
  hosts: localhost
  user: stibi
  roles:
    - mek

#- name:
# TODO: machine specific playbooks
# mek
# malina
# oblacek
